### ISSUE TITLE
Infer JSON::Class

### ISSUE THREAD

**Issue by con-mo8** [jonathanstowe/JSON-Infer#2]
Might be nice to have the inferred classes extend your JSON::Class so that they can be round tripped to/from the server?

**Comment by jonathanstowe** [comment]
To be honest I thought they did, but it wouldn't be the first time I've got a false memory about some software I've made.

I'll take a look.

**Comment by jonathanstowe** [comment]
Just had a look and the generated classes definitely do compose JSON::Class, there's a test for it and everything :)

If you've got an example where it's not working then I'd definitely want to know about it though.

**Comment by jonathanstowe** [comment]
I guess that's closed then
